### ISSUE TITLE
📌 TODO LIST

### ISSUE THREAD

**Issue by jms0522** [jms0522/Medical-project#60]
[https://dataengineeri-ymu7433.slack.com/files/T05M51ACQGK/F06KL56MX6H](0221)

**Comment by jms0522** [comment]
# 0203 todolist
---
민수 : 
민석 : 
승표 : 
성철 : 

- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by jms0522** [comment]
0224 ~ 0225 todolist  
참조 (회의기록) : #68
@stfano  @minseok1994 @cheol2Y 
## 민수

- [ ] 전처리한 데이터로 모델 학습 (deepspeed, auto advanced train)
- [ ] 학습 완료 시 허깅 페이스에 모델 올리기
- [ ] [DeepSpeed를 이용한 모델 학습](https://github.com/jms0522/Medical-project/issues/39#issuecomment-1959166735)
## 민석

- [ ] React 통한 was페이지 구축(뷰 페이지까지)
- [ ] Django 통한 web페이지 구축(api 연결을 위한 사전 작업)
- [x] Next.js 소스코드를 통한 웹 페이지 구축(학습중)

## 승표
- [ ] hugginface에 모델올리기 및 불러와서 확인 진행 (전처리 데이터 이용)
- [ ] 모델 변경으로 학습하고 허깅페이스에 올리기
- [ ] 효과적인 방법 찾기

## 성철
- [ ] kict 서버 연결 (중요)

## 공통
- [ ] 팀원 회의
- [ ] 웹 페이지 디지안 논의
- [ ] 자신이 작업한 결과물 민수한테 주거나 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

**Comment by jms0522** [comment]
0226 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 

## 민수

- [ ] 모델 파이프라인 구성 진행
- [ ] git action 웹 으로 테스트 (configure)
- [ ] 구축하는 파이프라인에 따른 필요한 알람 제작

--------------------------------------------------
## 민석

- [ ] React 통한 was페이지 구축(뷰 페이지까지)
- [ ] Django 통한 web페이지 구축(api 연결을 위한 사전 작업)
- [ ] 모델 파이프라인 구성 진행
- [ ] git action 웹 으로 테스트 (configure)

--------------------------------------------------
## 승표
- [ ] 22일에 진행했던 전처리 전 모델과 전처리 후 학습한 모델 결과 비교해보기 
- [ ] 모델바꿔서 테스트 데이터로 파인튜닝 및 결과 확인하기 (결과 좋다면 huggingface에 올리기)
- [ ] 모델 파이프라인 구성 진행


--------------------------------------------------
## 성철
- [ ] kict 서버 연결 (중요)
- [ ] 모델 파이프라인 구성 진행
- [ ] git action 웹 으로 테스트 (configure)

--------------------------------------------------
## 공통
- [ ] 팀원 회의
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡

**Comment by jms0522** [comment]
0228 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 

--------------------------------------------------
## 민수

- [ ] grafana 설치 및 패널 설정, postgresql
- [ ] 정처기 공부 오후

--------------------------------------------------
## 민석

- [ ] 간단한 vector store 구성 후 api 참조 테스트
- [ ] log message 출력하는 방식 고민
- [ ] 서비스 버튼에서 event 로그 발생 로직

--------------------------------------------------
## 승표

- [ ] airflow dag 구성 ( 크롤링 -> 전처리 -> 저장)
- [ ] 네이버 닥터나우 (자동 크롤링 코드 전처리 함수 넣어서 dag 생성)

--------------------------------------------------
## 성철

- [ ] 파이프라인 자동화 코드 구성  
- [ ] airflow dag 구성 ( 크롤링 -> 전처리 -> 저장)

--------------------------------------------------
## 공통

- [x] 팀원 회의
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡

**Comment by jms0522** [comment]
0228 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 

--------------------------------------------------
## 민수

- [ ] grafana로 다양한 모니터링과 alert 기능 활용
- [ ] 정처기 공부 (금요일 시험)

--------------------------------------------------
## 민석

- [ ] 전처리한  vector store 구성 후 api 참조 테스트 (모델 성능 올리기)
- [ ] 챗봇 ver.1 .1 구축 (기능 추가 될 때마다 version 바꾸면서 test
- [ ] 서비스 버튼에서 event 로그 발생 로직

--------------------------------------------------
## 승표

- [ ] airflow dag 구성 ( 크롤링 -> 전처리 -> 저장)
- [ ] 데이터 파이프라인 고도화
- [ ] 전처리 된 데이터가 db에 저장되고, 그에 따라 학습, 분석을 할 수 있는 인프라 구축

--------------------------------------------------
## 성철

- [ ] 파이프라인 자동화 코드 구성  
- [ ] 데이터 파이프라인 고도화

--------------------------------------------------
## 공통

- [ ] 팀원 회의 (멘토링 5시)
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡

**Comment by jms0522** [comment]
#0301 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] grafana로 다양한 모니터링과 alert 기능 활용
- [ ] 전처리 후 제대러 된 vector db 제작
- [ ] ec2 모니터링 툴 로컬에서 test

--------------------------------------------------
## 민석

챗봇 ver.1.1(DB연결)
- [ ] 사용자 웹 이벤트 로그 저장
- [ ] 사용자 서비스 로그 저장
- [ ] vector store 저장 방식 변경(로컬-> db), api 참조 테스트

--------------------------------------------------
## 승표

- [ ] 성철과 dag 합쳐서 하나의 docker compose 구성하기
- [ ] 데이터 전처리 고도화 진행 (어떻게 진행 했는지 회의)

--------------------------------------------------
## 성철

- [ ] 크롤링 데이터 및 전처리 최적화
- [ ] Airflow, Dag Docker-compose 구현해놓기
- [ ] 데이터 전처리 고도화 진행 (어떻게 진행 했는지 회의)

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
오늘 과업 못 하시면 내일로 넘어가고
내일도 못 하시면 그래도 적습니다.
오늘 과업 밀리진 않게 해주세요~ 확인하시고 ✅ 눌러주세요

**Comment by jms0522** [comment]
#0304 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] grafana로 다양한 모니터링과 alert 기능 활용
- [ ] 전처리 된 vector db 제작
- [ ] ec2 모니터링 툴 로컬에서 test

--------------------------------------------------
## 민석

- [ ] 챗봇 ver.1.1(DB연결)
- [ ] 사용자 웹 이벤트 로그 저장
- [ ] 사용자 서비스 로그 저장
- [ ] vector store 저장 방식 변경(로컬-> db), api 참조 테스트

--------------------------------------------------
## 승표

- [ ] 성철과 dag 합쳐서 하나의 docker compose 구성하기
- [ ] 데이터 전처리 고도화 진행 (어떻게 진행 했는지 회의)

--------------------------------------------------
## 성철

- [x] 크롤링 데이터 및 전처리 최적화
- [ ] Airflow, Dag Docker-compose 구현해놓기
- [x] 데이터 전처리 고도화 진행 (어떻게 진행 했는지 회의)
- [ ] 지식백과 데이터 전처리
--------------------------------------------------
## 공통

- [ ] 팀원 회의  (14:30 팀원 허들 회의 있습니다)
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0305 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 전처리 된 vector db 제작, 그래프 Db 이용해보기 
- [ ] airflow dag grafana 연결

--------------------------------------------------
## 민석

- [ ]  프롬포트와 청크 튜닝

--------------------------------------------------
## 승표

- [ ] 프롬포트 , 청크 튜닝으로 모델 완성 v2


--------------------------------------------------
## 성철

- [ ] Airflow, Dag Docker-compose 구현 완료해서 모니터링 
--------------------------------------------------
## 공통

- [ ] 팀원 회의  
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#03066 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] medicine 데이터 전처리
- [ ] neo4j로 diease와 medicine 관계 맺고 vector store로 제작.
- [ ] Master ec2 작업 (전부 연동)

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  Master ec2 작업 (전부 연동)

--------------------------------------------------
## 승표

- [x] 서비스 하나 로직 구현 및 진행해보기
- [ ] 서비스를 위한 vector db 제작
- [ ] Master ec2 작업 (전부 연동)

--------------------------------------------------
## 성철

- [ ] 닥터나우 dag 생성 (batch 주기 짧게)
- [ ] Master ec2 작업 (전부 연동)

--------------------------------------------------
## 공통

- [ ] 팀원 회의  (멘토링)
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0307 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] Master ec2 작업 (전부 연동)
- [ ] 모델에 추가할 정보 (모델 확장 고민)

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  Master ec2 작업 (전부 연동)

--------------------------------------------------
## 승표

- [ ] Master ec2 작업 (전부 연동)
- [ ] 유사 답변 로직 생성

--------------------------------------------------
## 성철

- [ ] 닥터나우 dag 생성 (batch 주기 짧게)
- [ ] Master ec2 작업 (전부 연동)

--------------------------------------------------
## 공통

- [x] 팀원 회의  (멘토링)
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0308 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] Master ec2 작업 (전부 연동)
- [ ] 모델에 추가할 정보 (모델 확장 고민)

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  Master ec2 작업 (전부 연동)

--------------------------------------------------
## 승표

- [ ] Master ec2 작업 (전부 연동)
- [x] 유사 답변 로직 생성

--------------------------------------------------
## 성철

- [x] 닥터나우 dag 생성 (batch 주기 짧게)
- [x] Master ec2 작업 (전부 연동)

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0308 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] elk pipeline 구축 (docker)
- [ ] docker container 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용

--------------------------------------------------
## 승표

- [ ] 서비스 로직 완성 (vector store)

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0310 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] elk pipeline 구축 (docker)
- [ ] docker container 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용

--------------------------------------------------
## 승표

- [ ] 서비스 로직 완성 (vector store)

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0311 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] elk pipeline 구축 (docker)
- [ ] docker container 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용

--------------------------------------------------
## 승표

- [x] 서비스 로직 완성 (vector store)

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0312 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 각 dag 별 logstash
- [ ] docker container 시각화
- [ ] grafana랑 kibana로 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용
- [ ]  airflow dag (vector store)

--------------------------------------------------
## 승표

- [ ]  airflow dag (vector store)

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0313 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 각 dag 별 logstash
- [ ] docker container 시각화
- [ ] grafana랑 kibana로 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용
- [ ]  airflow dag (vector store)

--------------------------------------------------
## 승표

- [ ]  airflow dag (vector store)

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0313 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 각 dag 별 logstash (hidak까지 완료)
- [ ] docker container 시각화
- [ ] grafana랑 kibana로 시각화

--------------------------------------------------
## 민석

- [ ]  web docker compose
- [ ]  서비스로직 web에 적용
- [ ]  airflow dag (vector store)

--------------------------------------------------
## 승표

- [ ]  airflow dag (vector store) (네이버 완, 하이닥, 닥터나우 진행) 
- [ ]  elastic search 데이터시각화를 위한 json 파일 dag 수정 

--------------------------------------------------
## 성철

- [ ] elk pipeline docker 구축 및 다양한 container 관리 방법
- [ ] airflow 슬랙 알람 
- [ ]  doctor now selenium 코드 변경 후 dag 제작 
--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0313 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] django dashboard
- [ ] 네이버 전체 데이터 elasticsearch - kibana 
- [ ] api (네이버 검색 , 카카오맵)

--------------------------------------------------
## 민석

- [ ] 로그 테이블 분리
- [ ] 크로마 db 연결
- [ ] 관리자 페이지 생성
- [ ] 페이지 추가

--------------------------------------------------
## 승표

- [ ] .
- [ ] .

--------------------------------------------------
## 성철

- [ ] lambda
- [ ] cloudwatch
- [ ] 서류 작업

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0315 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 대시 보드 테이블 시각화 세분화
- [ ] 네이버 전체 데이터 elasticsearch - kibana 올리기 (하이닥 전처리 완료되면 하이닥도) 
- [ ] 발표 자료 준비 

--------------------------------------------------
## 민석

- [ ] 페이지 디자인
- [ ] api 새로운 페이지에 더하기
- [ ] 관리자 페이지 생성


--------------------------------------------------
## 승표

- [x] doctornow elastic search를 위한 전처리
- [x] airflow drrc에 csv 전송 로직

--------------------------------------------------
## 성철

- [ ] 서류 작업
- [ ] ppt 생성 및 준비

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0315 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] 네이버 전체 데이터 elasticsearch - kibana 올리기 (하이닥 전처리 완료되면 하이닥도) 
- [ ] rabbitMQ exporter 
- [ ] CICD 

--------------------------------------------------
## 민석

- [ ] 페이지 디자인
- [ ] api 새로운 페이지에 더하기
- [ ] 관리자 페이지 생성


--------------------------------------------------
## 승표

- [ ] doctornow elastic search를 위한 전처리
- [ ] 유사질문 prompt engineering

--------------------------------------------------
## 성철

- [ ] 서류 작업
- [ ] ppt 생성 및 준비

--------------------------------------------------
## 공통

- [ ] 팀원 회의 
- [ ] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0318 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ]  logstast log 파이프라인
- [ ]  발표 자료 조사 

--------------------------------------------------
## 민석

- [ ]  EC2 이식
- [ ]  web 마무리

--------------------------------------------------
## 승표

- [ ] 발표 자료 조사
- [ ]  승표 하고 싶은 작업

--------------------------------------------------
## 성철

- [ ] 시스템 아키텍처 
- [ ] 발표 자료 준비
- [ ] 발표 ppt 준비 

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [x] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0319 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ]  logstast log 파이프라인
- [ ]  발표 자료 조사 
- [ ]  update dashboard 구축

--------------------------------------------------
## 민석

- [x]  EC2 이식
- [x]  web 마무리
- [ ]  logging 작업
- [ ]  django 시각화 세분화

--------------------------------------------------
## 승표

- [ ] 발표 자료 조사
- [x] airlflow dag 설정
- [ ]  airflow 전처리 함수 변경

--------------------------------------------------
## 성철

- [x] 시스템 아키텍처 
- [x] 발표 자료 준비
- [x] 발표 ppt 준비 

--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [x] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0321 todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## 민수

- [ ] PPT 제작

--------------------------------------------------
## 민석

- [ ] 모델 설계서
- [ ] API 정의서

--------------------------------------------------
## 승표

- [ ] 시연 영상 제작

--------------------------------------------------
## 성철

- [ ] 발표 대본 준비


--------------------------------------------------
## 공통

- [x] 팀원 회의 
- [x] 자신이 작업한 결과물 이슈에 주제별로 정리해서 업로드 (날짜 기입 필수)

--------------------------------------------------

오늘도 화이팅 🫡 
확인 하시면 ✅

**Comment by jms0522** [comment]
#0322 Todolist  
참조 (회의기록) : #68

@stfano  @minseok1994 @cheol2Y 
--------------------------------------------------
## ⚒️ 향후 보완 계획 
### 😁 Wish List

- [ ] Kubernetes를 활용한 Container Orchestration
- [ ] Graph Database를 통한 챗봇의 확장
- [ ] Web site Service 고도화 및 보안 취약점 제거
- [ ] 보다 많은 데이터를 처리할 수 있는 Pipeline 개발 및 유지 보수
- [ ] Jenkins , Git Action을 활용한 CI/CD 환경 구축
- [ ] ELK Stack을 활용한 보다 다양한 데이터 파이프라인
- [ ] 빅데이터와 그의 처리를 위한 Apache Kafka

--------------------------------------------------
## 3월 22일 마지막 Todolist Update

- [ ] 발표 
- [x] 원하는 기업에 취업
- [x] 3월 22일 (금) 회식 [막차 타기 없음]

--------------------------------------------------
확인 하시면 ✅

그 동안 저희 팀원 모드 너무 고생하셨습니다 :)
앞으로 좋은 결과 있길 바라고 감사했어요 🫡
